application: cs218-team2-chess-minimax
version: 1
runtime: python27
api_version: 1
instance_class: F4_1G
threadsafe: no
  
handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /static
  static_dir: static

- url: /.*
  script: cloud_chess_minimax.application